/*
 * This file is generated by jOOQ.
 */
package com.jooq.coversionIssue.jooq.codegen.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Testtable implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String nameVarchar;
    private String nameText;
    private String nameCitext;

    public Testtable() {}

    public Testtable(Testtable value) {
        this.id = value.id;
        this.nameVarchar = value.nameVarchar;
        this.nameText = value.nameText;
        this.nameCitext = value.nameCitext;
    }

    public Testtable(
        Integer id,
        String nameVarchar,
        String nameText,
        String nameCitext
    ) {
        this.id = id;
        this.nameVarchar = nameVarchar;
        this.nameText = nameText;
        this.nameCitext = nameCitext;
    }

    /**
     * Getter for <code>public.testtable.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.testtable.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.testtable.name_varchar</code>.
     */
    public String getNameVarchar() {
        return this.nameVarchar;
    }

    /**
     * Setter for <code>public.testtable.name_varchar</code>.
     */
    public void setNameVarchar(String nameVarchar) {
        this.nameVarchar = nameVarchar;
    }

    /**
     * Getter for <code>public.testtable.name_text</code>.
     */
    public String getNameText() {
        return this.nameText;
    }

    /**
     * Setter for <code>public.testtable.name_text</code>.
     */
    public void setNameText(String nameText) {
        this.nameText = nameText;
    }

    /**
     * Getter for <code>public.testtable.name_citext</code>.
     */
    public String getNameCitext() {
        return this.nameCitext;
    }

    /**
     * Setter for <code>public.testtable.name_citext</code>.
     */
    public void setNameCitext(String nameCitext) {
        this.nameCitext = nameCitext;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Testtable other = (Testtable) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.nameVarchar == null) {
            if (other.nameVarchar != null)
                return false;
        }
        else if (!this.nameVarchar.equals(other.nameVarchar))
            return false;
        if (this.nameText == null) {
            if (other.nameText != null)
                return false;
        }
        else if (!this.nameText.equals(other.nameText))
            return false;
        if (this.nameCitext == null) {
            if (other.nameCitext != null)
                return false;
        }
        else if (!this.nameCitext.equals(other.nameCitext))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.nameVarchar == null) ? 0 : this.nameVarchar.hashCode());
        result = prime * result + ((this.nameText == null) ? 0 : this.nameText.hashCode());
        result = prime * result + ((this.nameCitext == null) ? 0 : this.nameCitext.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Testtable (");

        sb.append(id);
        sb.append(", ").append(nameVarchar);
        sb.append(", ").append(nameText);
        sb.append(", ").append(nameCitext);

        sb.append(")");
        return sb.toString();
    }
}
