/*
 * This file is generated by jOOQ.
 */
package com.jooq.coversionIssue.jooq.codegen.tables.records;


import com.jooq.coversionIssue.jooq.codegen.tables.RegexpMatches;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RegexpMatchesRecord extends TableRecordImpl<RegexpMatchesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.regexp_matches.regexp_matches</code>.
     */
    public void setRegexpMatches(String[] value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.regexp_matches.regexp_matches</code>.
     */
    public String[] getRegexpMatches() {
        return (String[]) get(0);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RegexpMatchesRecord
     */
    public RegexpMatchesRecord() {
        super(RegexpMatches.REGEXP_MATCHES);
    }

    /**
     * Create a detached, initialised RegexpMatchesRecord
     */
    public RegexpMatchesRecord(String[] regexpMatches) {
        super(RegexpMatches.REGEXP_MATCHES);

        setRegexpMatches(regexpMatches);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RegexpMatchesRecord
     */
    public RegexpMatchesRecord(com.jooq.coversionIssue.jooq.codegen.tables.pojos.RegexpMatches value) {
        super(RegexpMatches.REGEXP_MATCHES);

        if (value != null) {
            setRegexpMatches(value.getRegexpMatches());
            resetChangedOnNotNull();
        }
    }
}
