/*
 * This file is generated by jOOQ.
 */
package com.jooq.coversionIssue.jooq.codegen.routines;


import com.jooq.coversionIssue.jooq.codegen.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.Internal;
import org.jooq.postgres.extensions.bindings.CitextBinding;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CitextLarger extends AbstractRoutine<String> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.citext_larger.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", DefaultDataType.getDefaultDataType("\"public\".\"citext\""), false, false, new CitextBinding());

    /**
     * The parameter <code>public.citext_larger._1</code>.
     */
    public static final Parameter<String> _1 = Internal.createParameter("_1", DefaultDataType.getDefaultDataType("\"public\".\"citext\""), false, true, new CitextBinding());

    /**
     * The parameter <code>public.citext_larger._2</code>.
     */
    public static final Parameter<String> _2 = Internal.createParameter("_2", DefaultDataType.getDefaultDataType("\"public\".\"citext\""), false, true, new CitextBinding());

    /**
     * Create a new routine call instance
     */
    public CitextLarger() {
        super("citext_larger", Public.PUBLIC, DefaultDataType.getDefaultDataType("\"public\".\"citext\""), new CitextBinding());

        setReturnParameter(RETURN_VALUE);
        addInParameter(_1);
        addInParameter(_2);
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    public void set__1(String value) {
        setValue(_1, value);
    }

    /**
     * Set the <code>_1</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void set__1(Field<String> field) {
        setField(_1, field);
    }

    /**
     * Set the <code>_2</code> parameter IN value to the routine
     */
    public void set__2(String value) {
        setValue(_2, value);
    }

    /**
     * Set the <code>_2</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void set__2(Field<String> field) {
        setField(_2, field);
    }
}
