/*
 * This file is generated by jOOQ.
 */
package com.jooq.coversionIssue.jooq.codegen;


import com.jooq.coversionIssue.jooq.codegen.tables.RegexpMatches;
import com.jooq.coversionIssue.jooq.codegen.tables.RegexpSplitToTable;
import com.jooq.coversionIssue.jooq.codegen.tables.Testtable;
import com.jooq.coversionIssue.jooq.codegen.tables.records.RegexpMatchesRecord;
import com.jooq.coversionIssue.jooq.codegen.tables.records.RegexpSplitToTableRecord;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.regexp_matches</code>.
     */
    public static final RegexpMatches REGEXP_MATCHES = RegexpMatches.REGEXP_MATCHES;

    /**
     * Call <code>public.regexp_matches</code>.
     */
    public static Result<RegexpMatchesRecord> REGEXP_MATCHES(
          Configuration configuration
        , String __1
        , String __2
    ) {
        return configuration.dsl().selectFrom(com.jooq.coversionIssue.jooq.codegen.tables.RegexpMatches.REGEXP_MATCHES.call(
              __1
            , __2
        )).fetch();
    }

    /**
     * Get <code>public.regexp_matches</code> as a table.
     */
    public static RegexpMatches REGEXP_MATCHES(
          String __1
        , String __2
    ) {
        return com.jooq.coversionIssue.jooq.codegen.tables.RegexpMatches.REGEXP_MATCHES.call(
            __1,
            __2
        );
    }

    /**
     * Get <code>public.regexp_matches</code> as a table.
     */
    public static RegexpMatches REGEXP_MATCHES(
          Field<String> __1
        , Field<String> __2
    ) {
        return com.jooq.coversionIssue.jooq.codegen.tables.RegexpMatches.REGEXP_MATCHES.call(
            __1,
            __2
        );
    }

    /**
     * The table <code>public.regexp_split_to_table</code>.
     */
    public static final RegexpSplitToTable REGEXP_SPLIT_TO_TABLE = RegexpSplitToTable.REGEXP_SPLIT_TO_TABLE;

    /**
     * Call <code>public.regexp_split_to_table</code>.
     */
    public static Result<RegexpSplitToTableRecord> REGEXP_SPLIT_TO_TABLE(
          Configuration configuration
        , String __1
        , String __2
    ) {
        return configuration.dsl().selectFrom(com.jooq.coversionIssue.jooq.codegen.tables.RegexpSplitToTable.REGEXP_SPLIT_TO_TABLE.call(
              __1
            , __2
        )).fetch();
    }

    /**
     * Get <code>public.regexp_split_to_table</code> as a table.
     */
    public static RegexpSplitToTable REGEXP_SPLIT_TO_TABLE(
          String __1
        , String __2
    ) {
        return com.jooq.coversionIssue.jooq.codegen.tables.RegexpSplitToTable.REGEXP_SPLIT_TO_TABLE.call(
            __1,
            __2
        );
    }

    /**
     * Get <code>public.regexp_split_to_table</code> as a table.
     */
    public static RegexpSplitToTable REGEXP_SPLIT_TO_TABLE(
          Field<String> __1
        , Field<String> __2
    ) {
        return com.jooq.coversionIssue.jooq.codegen.tables.RegexpSplitToTable.REGEXP_SPLIT_TO_TABLE.call(
            __1,
            __2
        );
    }

    /**
     * The table <code>public.testtable</code>.
     */
    public static final Testtable TESTTABLE = Testtable.TESTTABLE;
}
